# Site settings
title: Family Recipes
email: 
description: Family Recipes
baseurl: "https://mitch9378.github.io/family-recipes/recipes"
twitter_username:
github_username: 

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

